"use client";

import { useState } from "react";
import Script from "next/script";
import MerchantSidebar from "@/components/dashboard/MerchantSidebar";
import MerchantNavbar from "@/components/dashboard/MerchantNavbar";
import { Copy, Check, Play, ShieldAlert, Sparkles, Code2 } from "lucide-react";

export default function PaymentButtonsPage() {
  const [paymentId, setPaymentId] = useState("pay_demo_summer_drop_123");
  const [buttonText, setButtonText] = useState("Pay ₹499 via UPI");
  const [buttonTheme, setButtonTheme] = useState<"dark" | "blue" | "upi">("blue");
  const [copied, setCopied] = useState(false);

  const getStyleClass = () => {
    switch (buttonTheme) {
      case "dark":
        return "background: #0f172a; color: #ffffff; border-radius: 12px; padding: 12px 24px; font-weight: 600; font-size: 14px; border: none; cursor: pointer; display: inline-flex; align-items: center; gap: 8px;";
      case "upi":
        return "background: #0f8e5b; color: #ffffff; border-radius: 12px; padding: 12px 24px; font-weight: 600; font-size: 14px; border: none; cursor: pointer; display: inline-flex; align-items: center; gap: 8px;";
      case "blue":
      default:
        return "background: #0c8ee9; color: #ffffff; border-radius: 12px; padding: 12px 24px; font-weight: 600; font-size: 14px; border: none; cursor: pointer; display: inline-flex; align-items: center; gap: 8px;";
    }
  };

  const origin = typeof window !== "undefined" ? window.location.origin : "http://localhost:3000";

  const codeSnippet = `<!-- 1. Include BharatUPI Embed SDK -->
<script src="${origin}/sdk.js"></script>

<!-- 2. Embeddable Button (No secret keys exposed) -->
<button
  data-gateway-payment="${paymentId}"
  style="${getStyleClass()}"
>
  ${buttonText}
</button>`;

  const jsSnippet = `// Or trigger programmatically via JavaScript
BharatPay.open({
  paymentId: "${paymentId}",
  onComplete: function(response) {
    console.log("Payment status:", response.status, "RRN:", response.rrn);
  }
});`;

  const handleCopy = () => {
    navigator.clipboard.writeText(codeSnippet);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleTestModal = () => {
    if (typeof (window as any).BharatPay !== "undefined") {
      (window as any).BharatPay.open({ paymentId });
    } else {
      alert("SDK script loaded. Try clicking the button below or ensure paymentId exists.");
    }
  };

  return (
    <div className="flex min-h-screen bg-slate-50">
      <Script src="/sdk.js" strategy="afterInteractive" />
      <MerchantSidebar businessName="Swag Fashion Retail" />

      <div className="flex-1 flex flex-col min-w-0">
        <MerchantNavbar userEmail="merchant@swagfashion.in" />

        <main className="p-6 sm:p-8 space-y-6 max-w-7xl">
          <div>
            <h1 className="text-xl font-bold text-slate-900">Payment Buttons</h1>
            <p className="text-xs text-slate-500">
              Embeddable drop-in UPI checkout button for custom websites, apps, and landing pages
            </p>
          </div>

          {/* Compliance note */}
          <div className="rounded-xl border border-blue-200 bg-blue-50/70 p-4 text-xs text-blue-900 flex items-start gap-3">
            <ShieldAlert className="h-4 w-4 flex-shrink-0 text-blue-600 mt-0.5" />
            <div>
              <span className="font-bold">Zero Secret Exposure Principle:</span>
              <p className="mt-0.5 text-blue-800">
                Secret API keys are NEVER embedded in client-side code. Payment IDs are generated by your secure backend and passed to the frontend button.
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Customizer */}
            <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-xs space-y-4">
              <h2 className="text-sm font-bold text-slate-900">Button Configuration</h2>

              <div>
                <label className="text-xs font-semibold text-slate-700">Payment ID *</label>
                <input
                  type="text"
                  value={paymentId}
                  onChange={(e) => setPaymentId(e.target.value)}
                  placeholder="pay_xxxxxxxxxxxx"
                  className="mt-1 w-full rounded-xl border border-slate-200 px-3.5 py-2 text-xs font-mono text-slate-900 outline-none focus:border-blue-600"
                />
                <p className="mt-1 text-[11px] text-slate-400">
                  Created via <code>POST /api/v1/payments</code> on your server.
                </p>
              </div>

              <div>
                <label className="text-xs font-semibold text-slate-700">Button Label</label>
                <input
                  type="text"
                  value={buttonText}
                  onChange={(e) => setButtonText(e.target.value)}
                  className="mt-1 w-full rounded-xl border border-slate-200 px-3.5 py-2 text-xs text-slate-900 outline-none focus:border-blue-600"
                />
              </div>

              <div>
                <label className="text-xs font-semibold text-slate-700">Color Theme</label>
                <div className="mt-1 flex gap-2">
                  <button
                    type="button"
                    onClick={() => setButtonTheme("blue")}
                    className={`flex-1 rounded-xl py-2 text-xs font-semibold border ${
                      buttonTheme === "blue" ? "bg-blue-50 border-blue-600 text-blue-700" : "border-slate-200 text-slate-600"
                    }`}
                  >
                    Bharat Blue
                  </button>
                  <button
                    type="button"
                    onClick={() => setButtonTheme("upi")}
                    className={`flex-1 rounded-xl py-2 text-xs font-semibold border ${
                      buttonTheme === "upi" ? "bg-emerald-50 border-emerald-600 text-emerald-700" : "border-slate-200 text-slate-600"
                    }`}
                  >
                    UPI Green
                  </button>
                  <button
                    type="button"
                    onClick={() => setButtonTheme("dark")}
                    className={`flex-1 rounded-xl py-2 text-xs font-semibold border ${
                      buttonTheme === "dark" ? "bg-slate-100 border-slate-900 text-slate-900" : "border-slate-200 text-slate-600"
                    }`}
                  >
                    Dark Slate
                  </button>
                </div>
              </div>

              {/* Live Preview */}
              <div className="pt-4 border-t border-slate-100">
                <span className="text-xs font-semibold text-slate-700 block mb-3">Live Interactive Preview</span>
                <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50/60 p-6 flex flex-col items-center justify-center gap-2">
                  <button
                    data-gateway-payment={paymentId}
                    onClick={handleTestModal}
                    className={`px-6 py-3 rounded-xl font-bold text-xs text-white shadow-md transition ${
                      buttonTheme === "blue"
                        ? "bg-blue-600 hover:bg-blue-700"
                        : buttonTheme === "upi"
                        ? "bg-emerald-600 hover:bg-emerald-700"
                        : "bg-slate-900 hover:bg-slate-800"
                    }`}
                  >
                    {buttonText}
                  </button>
                  <span className="text-[10px] text-slate-400">Click to test SDK modal popup</span>
                </div>
              </div>
            </div>

            {/* Generated Code */}
            <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-xs flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between mb-2">
                  <h2 className="text-sm font-bold text-slate-900">Embed Code Snippet</h2>
                  <button
                    onClick={handleCopy}
                    className="flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-1 text-xs font-semibold text-slate-700 hover:bg-slate-50"
                  >
                    {copied ? (
                      <>
                        <Check className="h-3.5 w-3.5 text-emerald-600" />
                        <span className="text-emerald-600">Copied</span>
                      </>
                    ) : (
                      <>
                        <Copy className="h-3.5 w-3.5" />
                        <span>Copy HTML</span>
                      </>
                    )}
                  </button>
                </div>

                <pre className="rounded-xl bg-slate-950 p-4 text-xs font-mono text-slate-200 overflow-x-auto leading-relaxed border border-slate-800">
                  <code>{codeSnippet}</code>
                </pre>

                <h3 className="text-xs font-bold text-slate-800 mt-5 mb-2">JavaScript API Usage</h3>
                <pre className="rounded-xl bg-slate-950 p-4 text-xs font-mono text-emerald-400 overflow-x-auto leading-relaxed border border-slate-800">
                  <code>{jsSnippet}</code>
                </pre>
              </div>

              <div className="mt-4 pt-4 border-t border-slate-100 text-xs text-slate-500">
                The SDK automatically attaches to buttons marked with <code>data-gateway-payment</code> and opens a secure responsive checkout modal.
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
